services:
  api:
    build: .
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: PostgresPassword505
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      start_period: 1s
      retries: 5
    restart: always