name: Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: PostgresPassword505
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Compose services
        run: docker compose build

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Wait for services to be ready
        run: |
          until docker compose exec -T api curl -f http://localhost:80/docs; do
            sleep 5
          done

      - name: Run tests
        run: docker compose exec api pytest
